## In this Notebook:

- **Dataset**
- **Data Collection**
- **Import of Libraries**
- **Identifying Missing Values**
    - **Dropping High Percentage Missing Value Columns**
- **Checking Datatypes for All Columns**
    - **Datatype Conversions**
    - **Dropping the columns Combined**
- **Exporting the prepared dataset into CSV**

### Dataset

The dataset is a collection of traffic stops performed by police officers. This data is isolated to the state of **Rhode Island** (designated by the abbreviation RI).

### Data Collection

The data is collected by the Stanford Open Policing Project.

### Import of Libraries

In [1]:
#importing the pandas library to handle actions on the dataframe
import pandas as pd

#storing dataset in the RI_traffic dataframe
RI_traffic = pd.read_csv("Traffic_Stops_RI.csv")
RI_traffic.head()

,state,stop_date,stop_time,county_name,driver_gender,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district
0,RI,2005-01-04,12:55,NaN,M,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False,Zone X4
1,RI,2005-01-23,23:15,NaN,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
2,RI,2005-02-17,04:15,NaN,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X4
3,RI,2005-02-20,17:15,NaN,M,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False,Zone X1
4,RI,2005-02-24,01:20,NaN,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X3

- Each row represents one traffic stop.

In [2]:
RI_traffic.shape

(91741, 15)

### Identifying Missing Values

In [3]:
percent_missing = RI_traffic.isnull().sum() * 100 / len(RI_traffic)
percent_missing

state                   0.000000
stop_date               0.000000
stop_time               0.000000
county_name           100.000000
driver_gender           5.673581
driver_race             5.670311
violation_raw           5.670311
violation               5.670311
search_conducted        0.000000
search_type            96.395287
stop_outcome            5.670311
is_arrested             5.670311
stop_duration           5.670311
drugs_related_stop      0.000000
district                0.000000
dtype: float64

Columns with Missing values in the same count, 5,202:
- driver_gender
- driver_race
- violation_raw
- violation
- stop_outcome
- is_arrested
- stop_duration

**Questions** : 
- Could these associations in missing values be signicant and inform something about the data?
- Or can we drop these columns with highest missing values?
    - county_name at 100% missing
    - search_type at 96% missing

#### Dropping the highest percentage missing values

***Why?***  Since the percentage of missing values is so high, it's best to eliminate these columns as they will not serve with any value to replace or impute or manipulate.

In [4]:
#dropping the specific columns mentioned above
RI_traffic.drop(["county_name", "search_type", 
                 "state"], axis = 'columns', inplace=True)
                #also dropping state here because we already know this is just RI data
RI_traffic.head()

,stop_date,stop_time,driver_gender,driver_race,violation_raw,violation,search_conducted,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district
0,2005-01-04,12:55,M,White,Equipment/Inspection Violation,Equipment,False,Citation,False,0-15 Min,False,Zone X4
1,2005-01-23,23:15,M,White,Speeding,Speeding,False,Citation,False,0-15 Min,False,Zone K3
2,2005-02-17,04:15,M,White,Speeding,Speeding,False,Citation,False,0-15 Min,False,Zone X4
3,2005-02-20,17:15,M,White,Call for Service,Other,False,Arrest Driver,True,16-30 Min,False,Zone X1
4,2005-02-24,01:20,F,White,Speeding,Speeding,False,Citation,False,0-15 Min,False,Zone X3

In [5]:
#checking the shape of the dataframe again
RI_traffic.shape

(91741, 12)

- Successfully dropped the three columns

### Checking Data Types of All Columns

In [6]:
RI_traffic.dtypes

stop_date             object
stop_time             object
driver_gender         object
driver_race           object
violation_raw         object
violation             object
search_conducted        bool
stop_outcome          object
is_arrested           object
stop_duration         object
drugs_related_stop      bool
district              object
dtype: object

**Question**: Do we need to change any of these datatypes to make more sense?

*Changes that make sense:*

- Convert into a single column as datetime format:
    - **stop_date**: is object datatype however, it should be set to datetime
    - **stop_time**: is object datatype however, it should be timestamp

- Convert into Categorical:

    - **driver_gender**: This is a object but should be categorical

- Convert into Boolean
    - **is_arrested**: this is an object datatime, that should be converted into boolean


*Columns that can remain as they are:*

- Booleans that can remain booleans:
    - **search_conducted**: is a T/F boolean datatype, can accurately remain as is
    - **drugs_realted_stop**: is a T/F boolean datatype, and can remain as such
 
    
- Objects (ie. strings) that can remain objects:
    - **stop_outcome**: This is an object datatype, and can remain as is
    - **district**: This is an object datatype, and can remain as such since it's a string value
    - **violation_raw** & **violation**: can also remain objects
    - **driver_race**: can also remain as object
    - **stop_duration**: this can remain as is, unless deeemed necessary later

#### Datatype Conversions

##### Datetime Conversion of stop_date and stop_time

In [7]:
#1 - parse the date and replace the separator accordingly
#RI_traffic.stop_date.str.replace('/','-') #if it was necessary but in this case it's not
RI_traffic["date_time_stop"] = RI_traffic.stop_date.str.cat(RI_traffic.stop_time, sep = ' ')
RI_traffic

,stop_date,stop_time,driver_gender,driver_race,violation_raw,violation,search_conducted,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district,date_time_stop
0,2005-01-04,12:55,M,White,Equipment/Inspection Violation,Equipment,False,Citation,False,0-15 Min,False,Zone X4,2005-01-04 12:55
1,2005-01-23,23:15,M,White,Speeding,Speeding,False,Citation,False,0-15 Min,False,Zone K3,2005-01-23 23:15
2,2005-02-17,04:15,M,White,Speeding,Speeding,False,Citation,False,0-15 Min,False,Zone X4,2005-02-17 04:15
3,2005-02-20,17:15,M,White,Call for Service,Other,False,Arrest Driver,True,16-30 Min,False,Zone X1,2005-02-20 17:15
4,2005-02-24,01:20,F,White,Speeding,Speeding,False,Citation,False,0-15 Min,False,Zone X3,2005-02-24 01:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,21:21,F,Black,Other Traffic Violation,Moving violation,False,Citation,False,0-15 Min,False,Zone K2,2015-12-31 21:21
91737,2015-12-31,21:59,F,White,Speeding,Speeding,False,Citation,False,0-15 Min,False,Zone K3,2015-12-31 21:59
91738,2015-12-31,22:04,M,White,Other Traffic Violation,Moving violation,False,Citation,False,0-15 Min,False,Zone X3,2015-12-31 22:04
91739,2015-12-31,22:09,F,Hispanic,Equipment/Inspection Violation,Equipment,False,Warning,False,0-15 Min,False,Zone K3,2015-12-31 22:09
91740,2015-12-31,22:47,M,White,Registration Violation,Registration/plates,False,Citation,False,0-15 Min,False,Zone X4,2015-12-31 22:47

##### Dropping the columns Combined

In [8]:
RI_traffic.drop(["stop_date", "stop_time"], axis = 'columns', inplace=True)
RI_traffic

,driver_gender,driver_race,violation_raw,violation,search_conducted,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district,date_time_stop
0,M,White,Equipment/Inspection Violation,Equipment,False,Citation,False,0-15 Min,False,Zone X4,2005-01-04 12:55
1,M,White,Speeding,Speeding,False,Citation,False,0-15 Min,False,Zone K3,2005-01-23 23:15
2,M,White,Speeding,Speeding,False,Citation,False,0-15 Min,False,Zone X4,2005-02-17 04:15
3,M,White,Call for Service,Other,False,Arrest Driver,True,16-30 Min,False,Zone X1,2005-02-20 17:15
4,F,White,Speeding,Speeding,False,Citation,False,0-15 Min,False,Zone X3,2005-02-24 01:20
...,...,...,...,...,...,...,...,...,...,...,...
91736,F,Black,Other Traffic Violation,Moving violation,False,Citation,False,0-15 Min,False,Zone K2,2015-12-31 21:21
91737,F,White,Speeding,Speeding,False,Citation,False,0-15 Min,False,Zone K3,2015-12-31 21:59
91738,M,White,Other Traffic Violation,Moving violation,False,Citation,False,0-15 Min,False,Zone X3,2015-12-31 22:04
91739,F,Hispanic,Equipment/Inspection Violation,Equipment,False,Warning,False,0-15 Min,False,Zone K3,2015-12-31 22:09
91740,M,White,Registration Violation,Registration/plates,False,Citation,False,0-15 Min,False,Zone X4,2015-12-31 22:47

In [9]:
#convert to datetime datatype
RI_traffic["date_time_stop"] = pd.to_datetime(RI_traffic["date_time_stop"])
RI_traffic.dtypes

driver_gender                 object
driver_race                   object
violation_raw                 object
violation                     object
search_conducted                bool
stop_outcome                  object
is_arrested                   object
stop_duration                 object
drugs_related_stop              bool
district                      object
date_time_stop        datetime64[ns]
dtype: object

In [10]:
#Categorical conversion
RI_traffic['driver_gender'] = RI_traffic.driver_gender.astype('category')

#Bollean conversion
RI_traffic['is_arrested'] = RI_traffic.is_arrested.astype('bool')

RI_traffic.dtypes

driver_gender               category
driver_race                   object
violation_raw                 object
violation                     object
search_conducted                bool
stop_outcome                  object
is_arrested                     bool
stop_duration                 object
drugs_related_stop              bool
district                      object
date_time_stop        datetime64[ns]
dtype: object

### Exporting the prepared dataset

In [11]:
RI_traffic.to_csv('RI_traffic_prepped.csv')